sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-036
env:
  global:
    -
      # LTD_AWS_ID
      secure: cms6M/DZE1n9OU8Pa27QyLsQZQ24VPYzmYWyX0YBrUHp1H0h4f0qLEl6FI/nbDL677l/I+96gKboHxtOphTn7QklMBRzrtxCZ0jhAYz41tSzuySN45goW8nE9OjcGXGevhwaRqC0hxKyHLV7dFxQNdTQHFYhlaEc8glPhrzoE3UdYWtWWtWmZKRgOmvCM4CD5T0neKWLgl8Q3gOgdcdhvSpSHiBxqcFS9d1qt4LpAYxVxDO8Sy4jaLoOW1EC7qMMC7SUiZUeKvDZcUaW6VnwVfQCopO+WA8sutGVzYbYwxAKachWZhWmjC0gZZAdxf8/T+oGrmv3HSusJqpHBiFf6C0z+oBvRA8f9fPiRu4jMpxDYV16zPvct5KePbMUviuhfEQD2RpEVhf+nJoACIMATzBO1CpbkaRlwtFPlOnY7pjkG+fViIaoAoMNIlkQZL3WtVCH3RcVUhJWfSGBvhbYGF0vPqzMGL0kdeAFVi+xms4++Fm1XweabRkEJ0LBqmMMaBGimMbA5TeLJ1ys1JAmxIIr1ReXhid1zHYNzKmk3ij55gCD1G9T5vrRY9cNGbYXrTUC16YAsXNIODxAs/fmFPPStTgzsOYZ102EMPYHI2aJyGZYqfaUnWF9AyX8Rpq3NOdKFBvQYtIvpmwWAh2faIkkH2fxG4OYq4Lq5pOdG/E=
    -
      # LTD_AWS_SECRET
      secure: owiZBe1PViC1+lvkc0CyXegm9D/sU172Hro8dp/fbtHLT20qiDqF3Clvjd0iDQuqVStuSXjLbFq3qt8ahM9PCxtgXFcQfUlYscEpEvDm2kSAGpSOmSbnOcyLL3Fa4/nTtk2TxZ6sPzjgKUcWnCGcOHMwV0DSuASj7PEgfUJ8PD1aQZuCdVqqwGkeqM6nkXl58dCCaCJmyD6kMROtjMrLoIf5awEz5PTWBvkgkc9MuVU6m1C+azp/AKQYIv/9w/AwC9rgOaG3NSAaRW1r23va85T6QBJznAktkLeGJ3tOQ69cyb9YpDhPuW6jGfTY+3+Yz/Ayym9TxZp7hm8DCFtfDg2t/2fWhoHb1BHvMpmkHiWvbxxOTrUo/HQ1lpHZynHH+/qJkl7gxsmGB+kWZCYOpHr2zc8PeB/vFt+BfRaYfxXISjjUpi46p8nwVXuYJCTxL9zHCQ1zDtNfj9oq8BxW8DQoONryD9lGDvK1cZWC0QVz3k8AbKMTaVmdk3q3Atx9msQWyjQGgI5YqrtIIrR9K1qrTxIR7XoRCLrsgGV3AmHzaC52RMB9RpBjSbkRQluhw9kDrPeZlrN5Aheb80qXvxMDHkKjJgY8zMvR0oEjW6IZ1Ov17ImQmhC9TAhkxg4MYGNd8lVxceGlwe664ITvO8c6CIK9Gj9xaXakI0MA+9A=
    -
      # LTD_USERNAME
      secure: cPUEsddspCVw9+bkJVFQ7HvTo44QPfFQAGA9WrJu4X88WY795NkMJ/tO0/5cABcu5TqPPFcPV/BatHmzLsPb4a0gkP9PdP2GR8sD+bMyOA7F0yvmbGferfqTBrxftbxuO5tK40BSK7eeI3f2jv5OYL53bWkaYjuy7Q4zafHdWkGXv3jk1C7N6h8HWI84foi45ySVR9CXfOG1MKVKuXM0flG3xu+8WAZuQrfrjQqculp+/xJOPhrqDmgHkHUHm5B9XsmW6JfJDN0ZMyRVgbChUYjmQ1mhZot9yA5i4KdqqgYk0faguP/tWqEqOQ3BXOj4wSH8OLS83+CZCepTS4SZ8BLaBrSdLa/ZiI8yl5RlxNzMiVL0/FyDVEaXElLUHJ+3OT13MFWXaW1NQCAnQwgYNESTWXmbTmFVEyJdWJ+8o5VOtqVVdLv6gXOPlf9KiL2VctNvCYZDrji8O59LJGUaRS/Nb2pCP3xXBFO7J7vlFAJaGMy9TnTZND981umooXinbCTAjEygqngC4M1XOIL3pnYhIO1nHBqt+ZYx8pq00jFPbE14nyHHvZQ/dq2xYQ16Poh0hNQqH8EqGOgBbqYNMGCZnthjGNT1KJDlGpSBjGlHvx0CZi1NFYJw39/HSEMp+WdHluojIZ/U6/sAgVZSkrDlziQm+PjHdCoXdB/2ZLI=
    -
      # LTD_PASSWORD
      secure: cPm8WNhUpcILldvyiqO68hqqvt7UMGgXxiHMNcJ4191DwTVMVtpaCVaCU2JhE7ZTJW6um3/UcaJkmA2g75yvDuSpqwpcDz8Yyt8mvEhH5iorRnKz2SwX2obDu3EyICy03d2fua1Ke9Fa1LjTlytiamv79pRNiuMWJqEtusM/ip6kQEMVH6pUVN1zTQVrh65rLIzn8R8iA2dgOZySMfqWsMG3oH+ByNtybINrDtkopsK7bnI4JRzRVg5rfUzlkYaKdMricfZOfqcTttTP7XOgv7aiFddxrIjMVgo0DPiYNTB6utZxrJ9KLdMUpfLGiaRCcN6dlES3xhb4yQw2E4yfoSxBdKdntLOyVN8qfAcKIYzWafeXBTq5J/5Hk0NlsOtvCrdV7tpSUNT+m65vEMi+cHGjC+trC8v2yQt8vqNCd/m2BKquxhiaV/XfkLg8QpuosezDyAxbdNeFCUbd6qyh/L7Gq+aTa7oSebdWgIGAXFxXjxAgOun33AB+rgjWqTpHCG2R62RJuCojFVJrCA0G/q/qloPnrZGQ3ZxewTRJwT1jzvBPw5C1Y3a6gX41MG+m4Dn11wBUpTtUSCFLQSTALmbobWYduGJ5xqbMdWI5Kw5GdIcv6cpaiwNLquptPklb7mmK9jhC4dmihbSJWmeY5GrgJ6LcYkgsiiiUpVyV11Q=
